### ISSUE TITLE
USB module unavailable

### ISSUE THREAD

**Issue by Gaglios97** [schodet/nxt-python#168]
Hi!
When i try to run test_sensor.py on linux i have some problem...

I'm trying to run test_sensor.py with python3 because if i run with python2 i have problem with import nxt.locator, but when i run it i get these problems:

```
USB module unavailable, not searching there
Bluetooth module unavailable, not searching there
Traceback (most recent call last):
  File "test_sensors.py", line 6, in <module>
    b = nxt.locator.find_one_brick()
  File "/usr/local/lib/python3.5/dist-packages/nxt/locator.py", line 115, in find_one_brick
    for s in find_bricks(host, name, silent, method):
  File "/usr/local/lib/python3.5/dist-packages/nxt/locator.py", line 77, in find_bricks
    raise NoBackendError("No selected backends are available! Did you install the comm modules?")
nxt.locator.NoBackendError: No selected backends are available! Did you install the comm modules?
```

Did anyone have the same problem?

**Comment by schodet** [comment]
Please make sure that you have pyusb installed for USB, or pybluez for bluetooth, they must be installed for python3.
