### ISSUE TITLE
raise BlockedException("Blocked!")

### ISSUE THREAD

**Issue by Svein-Tore** [schodet/nxt-python#176]
HI!
I have come in to trouble with the motors.  I have created a program as  simple as this:

Import nxt.locator
from nxt.motor import * 
b=nxt.locator.find(host="00:16:53:0A:8A:50")
m_left = Motor(b, Port.B)
m_right = Motor(b, Port.C)
m_right.turn(100, 100,0)

When I run this program in terminal I expect that motor C should turn 100 degrees. Instead I get this error:

pi@raspberrypi:~/.local/bin $ python3 motortest.py
'Traceback (most recent call last):
  File "/home/pi/.local/bin/motortest.py", line 6, in <module>
    m_right.turn(100, 100,0)
  File "/home/pi/.local/lib/python3.9/site-packages/nxt/motor.py", line 272, in turn
    raise BlockedException("Blocked!")
nxt.motor.BlockedException: Blocked!

Any suggestions?  I'm using version 3.0.0a3 of NXT-Python.

**Comment by Svein-Tore** [comment]
Found the error. Now it works.
