### ISSUE TITLE
Silent failure with nxt-filer when brick is not plugged in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schodet/nxt-python#51]
```
When starting nxt_filer from a graphical desktop environment when no
Lego Mindstorm NXT is plugged in, for example using Alt-F2 in KDE,
nothing happen.   The program just silently fail to start, and do not
report any errors using the GUI.

Trying to run it from a shell show these messages:

% nxt_filer
Traceback (most recent call last):
  File "/usr/bin/nxt_filer", line 144, in <module>
    brick = nxt.locator.find_one_brick(keyword_arguments.get('host',None))
  File "/usr/lib/python2.6/dist-packages/nxt/locator.py", line 137, in find_one_brick
    raise BrickNotFoundError
nxt.locator.BrickNotFoundError
%

Please change the program to report this problem with a GUI popup or
something similar, to avoid confusing users trying to start the program
for the first time.



What version of nxt-python are you using? On what operating system? 2.2.2 on 
Debian GNU/Linux


Please provide any additional information below.

See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=697224 for the original 
Debian bug report.

```

Original issue reported on code.google.com by `sc...@kitterman.com` on 9 Apr 2013 at 1:11

**Comment by tcwan** [comment]
nxt-filer is obsolete.
There is a replacement, [nxtfilemgr](https://github.com/Eelviny/nxt-python/blob/master/scripts/nxtfilemgr), which can be found in the master branch.
