### ISSUE TITLE
Ultrasonic sensor: nxt.error.I2CError: read_value timeout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schodet/nxt-python#59]
```
What steps will reproduce the problem?

1. get a fresh install of nxt-python 2.2.2 working on Linux, connected to the 
brick via USB; the brick is running the latest leJOS firmware 0.9.1
2. check that the basic sensors (touch, sound) work nicely
3. then try accessing the ultrasonic sensor, even by running just:

#!/usr/bin/env python

import nxt.locator
from nxt.sensor import *
b = nxt.locator.find_one_brick()
ultrasonicSensor = Ultrasonic(b, PORT_3)

The output will be

Traceback (most recent call last):
  File "./test_ultrasonic.py", line 7, in <module>
    ultrasonicSensor = Ultrasonic(b, PORT_3)
  File "/usr/local/lib/python2.7/dist-packages/nxt/sensor/generic.py", line 95, in __init__
    super(Ultrasonic, self).__init__(brick, port, check_compatible)
  File "/usr/local/lib/python2.7/dist-packages/nxt/sensor/digital.py", line 73, in __init__
    sensor = self.get_sensor_info()
  File "/usr/local/lib/python2.7/dist-packages/nxt/sensor/digital.py", line 155, in get_sensor_info
    version = self.read_value('version')[0].split('\0')[0]
  File "/usr/local/lib/python2.7/dist-packages/nxt/sensor/digital.py", line 142, in read_value
    raise I2CError, "read_value timeout"
nxt.error.I2CError: read_value timeout

I believe that the leJOS firmware I am using is well stable (suggest 
differently otherwise) and I see that nxt-python had issues with the ultrasonic 
sensor before (e.g. issues no. 5 or 11). Perhaps the issue is still there.

In general, is the project still maintained? Thanks a lot.

Giacecco



```

Original issue reported on code.google.com by `giace...@giacecco.com` on 26 Aug 2013 at 2:13

**Comment by Nathan1123** [comment]
Hello. Is it known at least if this is a problem with nxt-python, or does it indicate anything wrong with the brick? I am having the same issue...

**Comment by GolddolphinSKB-Fexcraftian** [comment]
I'll have a look at this when I have time.

**Comment by osmarcedron** [comment]
#35, is a workaround

**Comment by schodet** [comment]
Dup of #35.
